# Generated by Django 3.2.6 on 2021-10-28 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('1', 'Activity is available to join!'), ('2', 'Activity is in progress!'), ('3', 'Activity ended!')], max_length=25)),
                ('currentUsers', models.IntegerField()),
                ('maxUsers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Other')], max_length=25)),
                ('location', models.CharField(max_length=150)),
                ('phoneNumber', models.CharField(max_length=25)),
                ('balance', models.FloatField()),
                ('frozenAccount', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sport', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('tutoringStatus', models.CharField(choices=[('1', 'Available'), ('2', 'Not available')], max_length=25)),
                ('tutorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='UserSkillReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.activity')),
                ('attendantUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendantUser', to='SportsCollaborationApp.siteuser')),
                ('reviewedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewedUser', to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='TutorshipReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=25)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='TutorshipModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tutorshipStatus', models.CharField(choices=[('1', 'In Progress'), ('2', 'Completed')], max_length=25)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('descriptiveString', models.CharField(max_length=50)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sport', models.CharField(max_length=100)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=25)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantOfActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.activity')),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('notificationStatus', models.CharField(choices=[('1', 'Sent Only'), ('2', 'Sent & Received')], max_length=25)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sourceUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sourceUser', to='SportsCollaborationApp.siteuser')),
                ('targetUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targetUser', to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('text', models.TextField(max_length=500)),
                ('time', models.TimeField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.messages')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantOfTutorship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantOfActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.activity')),
                ('siteUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('rating', models.CharField(choices=[('1', 1), ('2', 2), ('3', 3), ('4', 4), ('5', 5)], max_length=25)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.activity')),
                ('attendantUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='siteUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.siteuser'),
        ),
    ]
