# Generated by Django 3.2.6 on 2021-11-29 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0004_auto_20211129_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantofactivity',
            name='notification',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.notifications'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicantoftutorship',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SportsCollaborationApp.notifications'),
            preserve_default=False,
        ),
    ]
