# Generated by Django 3.2.6 on 2021-11-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0005_auto_20211129_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='siteUser',
        ),
        migrations.AddField(
            model_name='notifications',
            name='receiverSiteUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiverUser', to='SportsCollaborationApp.siteuser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='senderSiteUser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='senderUser', to='SportsCollaborationApp.siteuser'),
            preserve_default=False,
        ),
    ]
