# Generated by Django 3.2.6 on 2021-11-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0007_auto_20211130_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='notificationType',
            field=models.CharField(choices=[('1', 'Acknowledgement'), ('2', 'Request'), ('3', 'Rating')], max_length=25),
        ),
    ]
