# Generated by Django 3.2.6 on 2021-11-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0008_alter_notifications_notificationtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicantOfTutorship',
            new_name='ApplicantOfTutor',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RemoveField(
            model_name='activityrating',
            name='description',
        ),
        migrations.RemoveField(
            model_name='activityrating',
            name='title',
        ),
    ]
