# Generated by Django 3.2.6 on 2021-11-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0009_auto_20211130_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='pointerId',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
