# Generated by Django 3.2.6 on 2021-12-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0010_notification_pointerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='sport',
        ),
        migrations.AddField(
            model_name='tutor',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
