# Generated by Django 3.2.6 on 2021-12-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0011_auto_20211205_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
