# Generated by Django 3.2.6 on 2021-12-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0014_remove_directmessage_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicantOfTutor',
        ),
    ]
