# Generated by Django 3.2.6 on 2021-12-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0016_auto_20211206_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorshipmodel',
            name='tutorshipStatus',
        ),
    ]
