# Generated by Django 3.2.6 on 2021-12-06 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0018_auto_20211206_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorshipmodel',
            name='tutorshipStatus',
            field=models.CharField(choices=[('1', 'Ongoing'), ('2', 'Completed')], default=1, max_length=25),
            preserve_default=False,
        ),
    ]
