# Generated by Django 3.2.6 on 2021-12-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0019_tutorshipmodel_tutorshipstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notificationType',
            field=models.CharField(choices=[('1', 'Acknowledgement'), ('2', 'Request'), ('3', 'RatingActivity'), ('4', 'RatingTutor')], max_length=25),
        ),
    ]
