# Generated by Django 3.2.6 on 2021-12-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0020_alter_notification_notificationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='currentUsers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='maxUsers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='totalFee',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
