# Generated by Django 3.2.6 on 2021-12-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportsCollaborationApp', '0022_auto_20211208_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='totalFee',
            field=models.CharField(max_length=10),
        ),
    ]
